import { useState, useEffect } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const getdata = async () => {
  const res = await fetch('http://localhost:9090/api/echo/')
  const data = await res.json()
  return data?.msg
}

export default function Home() {
  const [msg, setMsg] = useState('')
  const [msg2, setMsg2] = useState('')

  useEffect(() => {
    fetch('http://localhost:9090/api/echo/')
      .then((resp) => resp.json())
      .then((data) => {
        console.log(data)
        setMsg(data?.msg)
      })

    fetch('http://localhost:9090/api/echo2/')
      .then((resp) => resp.json())
      .then((data) => {
        console.log(data)
        setMsg2(data?.msg)
      })
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h1>{msg}</h1>
      <h1>{msg2}</h1>
    </div>
  )
}
